### ISSUE TITLE
Support lat+long next to GLN

### ISSUE THREAD

**Issue by pimverkerk** [portofrotterdam/pronto-standards#7]
Global Location Numbers are recognised as the best way to identify a location. However most locations do not have such a number and the process of assigning one is time-consuming. In order to maintain momentum it could be an option to also support lat+long in combination with a location-type.

One of the expected downsides is that we will not be able to distinguish between two overlapping locations of the same type if no GLN is provided.

**Comment by dhoepelman** [comment]
Event location can now contain a subset of GeoJSON geometry as a `geo` field.
Either a `Point` defined by a lat+lng, for example this can be used by ships to give an E/ATA pilot boarding place on a certain geo location.
Or a `Polygon`, defined by a set of lat+lngs, for example this can be used by a port authority to give an PTA pilot boarding place with a certain area defining geo location of the pilot boarding place.
